name: github pages (not)

on:
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: toolchain for x86
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: "1.69.0"
        target: "x86_64-unknown-linux-gnu"
        default: true
        profile: minimal

    - name: toolchain for wasm
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: "1.69.0"
        target: "wasm32-unknown-unknown"
        default: false
        profile: minimal
        
    - name: "build vemf for x86_64"
      run: "cargo build --features bin --verbose"
    
    - name: "change script permissions"
      run: "chmod +x {doc,wasm}/do"
      
    - name: "make docs"
      run: |
        PATH="$PATH:$PWD/target/debug" doc/do && tail doc/docs.html
      
    - name: "make wasm"
      run: |
        set -ex
        curl -L "https://github.com/rustwasm/wasm-bindgen/releases/download/0.2.84/wasm-bindgen-0.2.84-x86_64-unknown-linux-musl.tar.gz" | tar -xvz
        curl -L "https://github.com/WebAssembly/binaryen/releases/download/version_112/binaryen-version_112-x86_64-linux.tar.gz" | tar -xvz
        mkdir esbuild
        curl "https://registry.npmjs.org/@esbuild/linux-x64/-/linux-x64-0.17.18.tgz" | tar -xvz --directory esbuild
        PATH="$PATH:$PWD/binaryen-version_112/bin:$PWD/esbuild/package/bin:$PWD/wasm-bindgen-0.2.84-x86_64-unknown-linux-musl" wasm/do
        
    - name: "make site ready"
      run: |
        set -ex
        mkdir _site
        mkdir _site/doc
        cp doc/docs.html _site/doc/docs.html
        mkdir _site/wasm
        cp wasm/index.html _site/wasm/index.html
        cp -r wasm/pkg _site/wasm/pkg
        tree _site
      
  # todo: actually figure out how to deploy
