name: github pages

on:
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: toolchain for x86
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: "1.69.0"
        target: "x86_64-unknown-linux-gnu"
        default: true
        profile: minimal
        
    - name: "change script permissions"
      run: "chmod +x doc/do"

    - name: "build vemf for x86_64"
      run: "cargo build --features bin --verbose"

    - name: "make docs"
      run: 'PATH="$PATH:$PWD/target/debug" doc/do'

    - name: "upload file"
      uses: actions/upload-artifact@v3
      with:
        name: docs
        path: doc/docs.html
    
  build-wasm:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: install nix
      uses: cachix/install-nix-action@v19
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: make app
      run:  "nix build ./wasm --verbose"

    - name: copy files  # See (https://github.com/actions/deploy-pages/issues/58)
      run: cp -r -L --no-preserve=mode,ownership result pkg

    - name: "upload file"
      uses: actions/upload-artifact@v3
      with:
        name: wasm_pkg
        path: pkg/

  deploy:
    needs:
    - build-docs
    - build-wasm
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: "checkout"
      uses: actions/checkout@v3

    - name: "setup directories and static data"
      run: |
        set -ex
        mkdir _site/{,doc,wasm}
        cp wasm/index.html _site/wasm/index.html
    
    - name: "download docs"
      uses: actions/download-artifact@v3
      with:
        name: docs
        path: _site/doc

    - name: "download wasm"
      uses: actions/download-artifact@v3
      with:
        name: wasm_pkg
        path: _site/wasm/pkg

    - name: "tree :)"
      run: tree -C _site
    
    - name: "configure GitHub Pages"
      uses: actions/configure-pages@v3.0.2

    - name: "upload pages artifact"
      uses: actions/upload-pages-artifact@v1.0.7

    - name: "deploy to GitHub Pages"
      id: deployment
      uses: actions/deploy-pages@v2